In [1]:
#exo1
import numpy as np
Tab1 = np.zeros(10)
Tab1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
Tab2 = np.ones(10)
Tab2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
Tab3 = np.ones(10)*5
Tab3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
Tab4 = np.arange(10,50)
Tab4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
Tab5 = np.arange(10,50,2)
Tab5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [20]:
Matrix = np.arange(0,9)
Matrix1 = np.array(Matrix).reshape(3,3)
Matrix1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
Matrix2 = np.eye(3)
Matrix2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
v = np.random.rand(1)
v

array([0.14675589])

In [44]:
B = np.random.randn(25)
B

array([-1.10593508, -1.65451545, -2.3634686 ,  1.13534535, -1.01701414,
        0.63736181, -0.85990661,  1.77260763, -1.11036305,  0.18121427,
        0.56434487, -0.56651023,  0.7299756 ,  0.37299379,  0.53381091,
       -0.0919733 ,  1.91382039,  0.33079713,  1.14194252, -1.12959516,
       -0.85005238,  0.96082   , -0.21741818,  0.15851488,  0.87341823])

In [50]:
Matrice = np.linspace(0.01 , 1,100)
Ma = np.array(Matrice).reshape(10,10)
Ma

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [62]:
Z = np.linspace(0,1,20)
Z

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
##########


In [63]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### mat[2:5 , 1:5]


In [68]:
mat [3][4]

20

In [84]:
v = mat [0:3 , 1]
v
d = np.array(v).reshape(3,1)
d

array([[ 2],
       [ 7],
       [12]])

In [85]:
mat [4]

array([21, 22, 23, 24, 25])

In [87]:
mat [3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [90]:
mat.sum()

325

In [91]:
w = np.std(mat)
w

7.211102550927978

In [6]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
c = mat [0:5 , 0]
c
v = mat [0:5 , 1]
v
c = v 
c

array([ 2,  7, 12, 17, 22])